name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: testManyNumbers
      id: testmanynumbers
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testManyNumbers
        setup-command: ''
        command: ' sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo
          update-locale && gradle test --tests "Prog42Test.testManyNumbers"'
        timeout: 10
        max-score: 4
    - name: testSingleNumber
      id: testsinglenumber
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testSingleNumber
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "Prog42Test.testSingleNumber"
        timeout: 10
        max-score: 4
    - name: testNoInput
      id: testnoinput
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testNoInput
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "Prog42Test.testNoInput"
        timeout: 10
        max-score: 4
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTMANYNUMBERS_RESULTS: "${{steps.testmanynumbers.outputs.result}}"
        TESTSINGLENUMBER_RESULTS: "${{steps.testsinglenumber.outputs.result}}"
        TESTNOINPUT_RESULTS: "${{steps.testnoinput.outputs.result}}"
      with:
        runners: testmanynumbers,testsinglenumber,testnoinput
